### ISSUE TITLE
System.IO.DirectoryNotFoundException with file "stations.txt"

### ISSUE THREAD

**Issue by sergiomarotco** [LRih/Train-Network-Simulator#1]
System.IO.DirectoryNotFoundException: "Не удалось найти часть пути "C:\Users\Sergiomarotco\Source\Repos\Train-Network-Simulator\bin\Debug\data\stations.txt"."

Can u add example of file "stations.txt" to the project and publish a release?

**Comment by sergiomarotco** [comment]
foreach (string line in File.ReadAllLines(DATA_PATH + "stations.txt"))

**Comment by LRih** [comment]
I've added example data files in the latest commit.
